### ISSUE TITLE
Provide a PEM representation of the certificate as an attribute

### ISSUE THREAD

**Issue by psevestre** [hashicorp/terraform-provider-tls#149] opened 2022-02-15 13:40 UTC
### Terraform CLI and Provider Versions

Terraform v1.0.11
on windows_amd64
+ provider registry.terraform.io/hashicorp/tls v3.1.0

### Use Cases or Problem Statement

In some scenarios, we need to retrieve self-signed certificates from a given server and feed it to several resources, usually in PEM-format.

Currently tls_certificate data source can retrieve a certificate, but there's no (easy) way to generate a PEM from it.

### Proposal

Add an additional property (e.g. "cert_pem" for consistency with the tls_self_signed_cert resource) to the current structure, containing the PEM-formatted cert.

### How much impact is this issue causing?

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yannik-beaulieu-ia** [comment] 2022-03-10 21:17
Any progress on this? That's something I need to dynamically assign certificates pulled from an URL.

Also seems to be a duplicate of #81

**Closed** 2022-05-16 16:50 UTC
Labels: enhancement
